# This workflow will build the project

name: Build MAUI App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
  
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Install MAUI workload
      run: dotnet workload install maui
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build OneApp/OneApp.csproj --no-restore -c debug -f:net7.0-andriod
    - name: Test
      run: dotnet test --no-build --verbosity normal
