name: Build and deploy Web app

env:
  AZURE_WEBAPP_NAME: oneapp-test
  AZURE_WEBAPP_PACKAGE_PATH: OneApp.API\publish
  DOTNET_VERSION: 8.0.x
  BUILD_CONFIGURATION: Release
  WORKING_DIRECTORY: OneApp.API

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

      - name: Build 🔨
        run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
      
      - name: Test
        run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
      
      - name: Publish 🚀
        run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}" 

      - name: Publish build artifact 📢
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    permissions:
      contents: none
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: web-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
